version: '3.7'
services:
  worker_1:
    build: .
    image: omnicrawl-worker
    shm_size: '4gb'
    environment:
      - BROWSER=${BROWSER}
      - HARDENED=${HARDENED}
      - START_IDX=0
      - END_IDX=50
      - PROXY_PORT=38080
      - DISPLAY_NUM=99
    volumes:
      - ./data:/app/data
      - ./brave_strict_profile:/app/brave_strict_profile

  worker_2:
    build: .
    image: omnicrawl-worker
    shm_size: '4gb'
    environment:
      - BROWSER=${BROWSER}
      - HARDENED=${HARDENED}
      - START_IDX=50
      - END_IDX=100
      - PROXY_PORT=38081
      - DISPLAY_NUM=100
    volumes:
      - ./data:/app/data
      - ./brave_strict_profile:/app/brave_strict_profile